In [42]:
import gym
from gym import spaces
from gym.utils.env_checker import check_env
import matplotlib.pyplot as plt
import numpy as np
from bucket_env import plot_stats
%matplotlib inline

In [43]:
import scipy.stats as stat

In [107]:
class ChompEnv(gym.Env):

    def __init__(self, m=4, n=5):
        self.m = m
        self.n = n
        self.max_m = m
        self.max_n = n
        self.action_space = spaces.Tuple((
            spaces.Discrete(self.m),
            spaces.Discrete(self.n)
        ))
        self.observation_space = spaces.Box(
            low=0,
            high=1,
            shape=(self.m, self.n),
            dtype=np.int32)
        self.state = np.zeros((self.m, self.n), dtype=np.int32)

    def step(self, action):
       
        row, col = action

        #Joueur 1 : 
        self.max_m = row
        self.max_n = col
        if self.state[row,col] == 1:
            reward = -1
            raise Exception("carré déjà mangé")
        self.state[row:, col:] = 1
        done = bool(np.all(self.state == 0))
        reward = 1 if done else 0

        #Joueur 2 :
        if np.any(self.state[row:,col:] == 1):
            possibilities = np.argwhere(self.state == 0)
            random_action = tuple(np.random.choice(possibilities)[0])
            row, col = random_action
            self.state[row:,col:] = 1
        done = np.all(self.state == 1)
        reward = 1 if done else 0
        return self.state, reward, done, {}

    def reset(self):
        self.state = np.zeros((self.m, self.n), dtype=np.int32)
        return self.state

    def render(self):
        print(self.state)



In [111]:
env = ChompEnv()
check_env(env)
env.reset()
env.step((0,3))
env.render()

[[0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 1 1]]


c:\Users\Romain\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\utils\env_checker.py:109: UserWarning: WARN: Your observation  has an unconventional shape (neither an image, nor a 1D vector). We recommend you to flatten the observation to have only a 1D vector or use a custom policy to properly process the data.
  logger.warn(
